### ISSUE TITLE
Unable to add a Channel with a period to a Channel Group 

### ISSUE THREAD

**Issue by drewrawitz** [pubnub/javascript#234]
Hello,

I'm trying to follow the documentation for adding channels to a channel group, and even using the exact same code outlined in the docs:

```
pubnub.channelGroups.addChannels({
   channels: ["chats.room1", "chats.room2", "alerts.system"],
   channelGroup: "cg_user123"
})
```

from: https://www.pubnub.com/docs/channels/subscribe#channel-groups

I get the following error:
```
text: '{"status": 400, "message": "Reserved character in input parameters.", "service": "channel-registry", "error": true}'`
```

If I remove the periods and just do `['chatsroom1', 'chatsroom2', 'alertssystem']` then it works just fine.  Any reason why this would be erroring out?  I'm under the impression that the period in channel names is valid, and [even recommended](https://www.pubnub.com/docs/channels/channel-naming#recommended-naming-convention).

Any help is appreciated. Thanks!

**Comment by raipubnub** [comment]
Correct, you cannot use a period in channel groups for pubnub, you can try using underscore or another character instead. Here is the documentation for reference -> https://www.pubnub.com/docs/channels/subscribe#channel-groups

**Comment by drewrawitz** [comment]
@raipubnub I did use an underscore for the channel group. The periods are in the channels which is used as an example in the docs link we both referenced.

**Comment by phairow** [comment]
Oh, I apologize, I didn't read the details. Was thinking this was the channel group naming issue.

**Comment by raipubnub** [comment]
I asked around and it looks like you can enable the ability to add channels with a `.` to channel groups by contacting the support team. [https://support.pubnub.com](https://support.pubnub.com). This may get enabled by default in the future but for existing accounts with the issue you can check with support for now.
