### ISSUE TITLE
SyntaxError: Unexpected string in vm2

### ISSUE THREAD

**Issue by bcanzanella** [pubnub/javascript#239]
hello!

I'm trying to upgrade to the latest pubnub (4.37.0) in our webpack'ed [nodejs app](https://github.com/TeamCodeStream/codestream/blob/develop/shared/agent/package.json#L70). It installs fine, but at runtime I see the following error which creates a fatal error:

```
/Users/bcanzanella/code/codestream/shared/agent/dist/agent.js:225193
	__webpack_require__("./node_modules/vm2/lib sync recursive"),
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at wrapSafe (internal/modules/cjs/loader.js:1033:16)
    at Module._compile (internal/modules/cjs/loader.js:1081:27)
    at Object..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at internal/modules/cjs/loader.js:823:14
    at Function._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

`vm2` appears to be a dependency of a dependency... from pubnub:

```
bcanzanella@C02FG42AMD6P:~/code/codestream/shared/agent [develop]$ npm list vm2
codestream-lsp-agent@0.0.2 /Users/bcanzanella/code/codestream/shared/agent
└─┬ pubnub@4.37.0
  └─┬ superagent-proxy@3.0.0
    └─┬ proxy-agent@5.0.0
      └─┬ pac-proxy-agent@5.0.0
        └─┬ pac-resolver@5.0.0
          └─┬ degenerator@3.0.1
            └── vm2@3.9.5 
```

pubnub version 4.33.1 works (which doesn't have a dependency on a dependency on vm2).

I just wanted to see if you had any guidance for how to resolve this? thanks!

**Comment by phairow** [comment]
Hmm, looks like vm2 is a dependency of superagent-proxy which we recently upgraded. We haven not tried using webpack with the nodejs build and have not seen this issue. Is it possible to share your webpack configuration or the relevant pieces of the configuration needed to reproduce the error?

**Comment by raipubnub** [comment]
What is the version of webpack?

**Comment by raipubnub** [comment]
I have created this github repository to attempt to reproduce the issue and I did not have an any errors using the latest webpack and pubnub versions -> [https://github.com/raipubnub/webpack_demo](https://github.com/raipubnub/webpack_demo.) I think this may be something specific to your configuration. Please contact PubNub support so we can investigate further.

**Comment by phairow** [comment]
the example repo is moved here -> https://github.com/phairow/webpack_demo
