### ISSUE TITLE
Buttons in smaller devices touches each other

### ISSUE THREAD

**Issue by hirentimbadiya** [pubnub/javascript#315]
Objects and Message Actions buttons should have some gap between them , this looks a bit ugly in smaller devices

![issue](https://user-images.githubusercontent.com/86219935/229285472-4b327557-3f7d-4f25-947c-07e60f4bdfa1.png)

**Comment by hirentimbadiya** [comment]
I  would like to work on this :)

**Comment by juhijoshi-coder** [comment]
Hey, @hirentimbadiya did you start working on it already, or Can I take it up? Thank you

**Comment by hirentimbadiya** [comment]
> Hey, @hirentimbadiya did you start working on it already, or Can I take it up? Thank you

you can start working on this

**Comment by shashankupadhyay03** [comment]
Hey @hirentimbadiya I want to work in this issue

**Comment by WebDevHarsha** [comment]
i would like to work on this issue.

**Comment by bawanetejas** [comment]
i also like to  work on this issue

**Comment by Ashish-singh-1112** [comment]
Is anyone working on this issue ? If not then I would like to work on this issue.
