### ISSUE TITLE
Button width is not responsive in smaller device

### ISSUE THREAD

**Issue by hirentimbadiya** [pubnub/javascript#316]
Button should take full width in smaller devices

![button width](https://user-images.githubusercontent.com/86219935/229285672-49f1d0a0-f6a5-48c6-8d05-f4d83e6f62b0.png)

**Comment by hirentimbadiya** [comment]
I would like to work on this :)

**Comment by techwritermat** [comment]
Thanks for bringing this to our attention, but it's not a JS SDK issue. We'll look into it!
