### ISSUE TITLE
deprecated superagent@6.1.0

### ISSUE THREAD

**Issue by wimZ** [pubnub/javascript#317]
Installing pubnub gives the following npm warning.

npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues
 with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are
 now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releas
es>.

**Comment by dawik** [comment]
We are seeing  this in our security scans as well

Can we get an acknowledgement of the issue? 

Any plans to upgrade?
