### ISSUE TITLE
PNNetworkIssuesCategory in ios ionic capacitor app

### ISSUE THREAD

**Issue by mohanve7** [pubnub/javascript#320]
i was using ionic 6 capacitor 4 app the chat is working fine in android but in ios throwing error

{"error":true,"operation":"PNSubscribeOperation","errorData":{"crossDomain":true,"method":"GET","url":"http://ps12.pndsn.com/v2/subscribe/sub-c-8b690ebb-d930-4e14-b537-4caf2bfd7d4e/user_171.store_13%2Cuser_171.store_13-pnpres/0?heartbeat=300&uuid=user_171&pnsdk=PubNub-JS-Web%2F7.2.2"},"category":"PNNetworkIssuesCategory"}

**Comment by Translucent504** [comment]
@mohanve7 Did you find a solution to this?

**Comment by mohanve7** [comment]
> @mohanve7 Did you find a solution to this?

just add ssl:true
 this.pubnub = Pubnub({
      // Please use your own sub and pub keys below
      subscribe_key: sub-key,
      publish_key:   pub-key
      ssl: true
  });
