### ISSUE TITLE
@types/pubnub missing getToken

### ISSUE THREAD

**Issue by sanbornhilland** [pubnub/javascript#333]
The @types/pubnub package is missing the `PubNub#getToken` method. This method is present on the `PubNub` class but not exposed via here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6be113476bef803465cd7e1a96a14a96154351f3/types/pubnub/index.d.ts#L140

Similar to #263 I'm wondering if this team maintains the DefinitelyTyped types package and if we can get that updated?

**Comment by mohitpubnub** [comment]
This issue is addressed in latest [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66378) at DefinitelyTyped.

**Comment by mohitpubnub** [comment]
closing this as relevant PR is merged
