### ISSUE TITLE
Case sensitive path issue

### ISSUE THREAD

**Issue by asapach** [pubnub/javascript#351]
There are two files that have the same name differing only in case:
- [`lib/crypto/modules/NodeCryptoModule/NodeCryptoModule.js`](https://github.com/pubnub/javascript/blob/master/lib/crypto/modules/NodeCryptoModule/NodeCryptoModule.js)
- [`lib/crypto/modules/NodeCryptoModule/nodeCryptoModule.js`](https://github.com/pubnub/javascript/blob/master/lib/crypto/modules/NodeCryptoModule/nodeCryptoModule.js)

This causes problems when files are moved between case-sensitive and insensitive file systems, e.g. linux → windows.

**Comment by mohitpubnub** [comment]
thanks for reporting and PR
this issue addressed in v7.5.0
