### ISSUE TITLE
decrypt method of legacyCryptoModule throws an error for unencrypted string values with "_" 

### ISSUE THREAD

**Issue by simform-manan-mankodi** [pubnub/javascript#353]
Hello,

We've recently updated our Pubnub SDK from version 4.33.1 to the latest 7.4.5 as the first step to use 256-bit encryption for better security, though the 256-bit encryption is not yet enabled. So far we have followed the steps mentioned in the guide [here](https://www.pubnub.com/how-to/upgrade-encryption-to-256-bit-key-length/#h-4). 

Due to a certain behavior change in the `decrypt` method, our web application is broken. We have a listener on the React web app to receive messages - which can be encrypted or unencrypted messages. For unencrypted messages/values, earlier the `pubnubInstance.decrypt()` method used to return `null`, but the new `cryptoModule.decrypt()` method throws an error whenever a value with character `_` is passed to it. Returns `null` as expected for a string value without `_`.

![pubnub_error](https://github.com/pubnub/javascript/assets/155444825/b6683af7-0eaf-4cf1-8b7d-9180d3249488)

Would it be possible to fix this and achieve the old behavior of returning `null` as expected? Is there any other way to handle both encrypted & unencrypted messages on the web app listener without trying to decrypt the unencrypted messages, thus avoiding this issue?

Thanks.

**Working snippet with v4.33.1:**

![pubnub_4_33_1_working](https://github.com/pubnub/javascript/assets/155444825/dd0b85a2-f62d-40dc-af2f-2549f3ab9b8e)

**Snippet having the issue with v7.4.5:**

![punub_latest_error](https://github.com/pubnub/javascript/assets/155444825/0fc195f9-2fb1-474b-b629-94d64e6dd6c0)

**Comment by mohitpubnub** [comment]
Initialising PubNub instance along with cryptoModule(`legacyCryptoModule` or `aesCbcCryptoModule`) won't break the listener in case of mixture of encrypted/unencrypted messages. pubnub initialisation with cryptoModule example snippet is [here](https://www.pubnub.com/docs/sdks/javascript/api-reference/configuration#basic-usage)

In the description code snippet, Message is being decrypted manually. In case of possible unencrypted message, we need to catch the error and return null. If we want to return null instead original unencrypted message

Reason: cryptoModules are able to decrypted both 128 and 256 bit encrypted messages for backward compatibility. So now `decrypt` method throws Error with error message about failure reason instead returning null. So that user of native decrypt method can handle various scenarios based on failure reason.

**Comment by mohitpubnub** [comment]
Also,

>Would it be possible to fix this and achieve the old behavior of returning null as expected?

one possible solution is: 
If PubNub instance is initialised with cryptoModule and if subscription received unencrypted message then
listener with receive message as it's original form and message.error will contain error message.
you can implement a quick logic to return null from there if there is any failure.

or try catch-error with manual decryption if that is compatible with other app logic!

**Comment by simform-manan-mankodi** [comment]
> Initialising PubNub instance along with cryptoModule(`legacyCryptoModule` or `aesCbcCryptoModule`) won't break the listener in case of mixture of encrypted/unencrypted messages. pubnub initialisation with cryptoModule example snippet is [here](https://www.pubnub.com/docs/sdks/javascript/api-reference/configuration#basic-usage)
> 
> In the description code snippet, Message is being decrypted manually. In case of possible unencrypted message, we need to catch the error and return null. If we want to return null instead original unencrypted message
> 
> Reason: cryptoModules are able to decrypted both 128 and 256 bit encrypted messages for backward compatibility. So now `decrypt` method throws Error with error message about failure reason instead returning null. So that user of native decrypt method can handle various scenarios based on failure reason.

Thank you so much for the quick response. We need to use manual decryption for now so will catch & handle the error accordingly. :+1: 

Also would like to request a couple of updates in the guide [here](https://www.pubnub.com/how-to/upgrade-encryption-to-256-bit-key-length/#h-4) in the section **If you are not specifying the cipher key as part of your PubNub configuration but encrypting messages as needed:**
- About mentioning the error handling change for the manual decryption method.
- About updating the statement **adding the CryptoModule to the SDKs was a non-breaking change** in the best feasible manner, as this small issue might be a breaking change for some users of JS SDK.

Thanks again!
