### ISSUE TITLE
Typings for new features (Event Engine & Listeners)

### ISSUE THREAD

**Issue by roman-rr** [pubnub/javascript#377]
Hello everyone. 

Could someone please help to update typings:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pubnub

Latest version is `"@types/pubnub": "7.4.2"` and PubNub `"pubnub": "8.0.1"`.

Especially need to have new methods from new **Event Engine & Listeners**, such as `subscriptionSet`. 

Thanks.

**Comment by parfeon** [comment]
@roman-rr  this issue is addressed in [v8.2.10](https://github.com/pubnub/javascript/releases/tag/v8.2.10)
