### ISSUE TITLE
REST API request processing error, check status for details

### ISSUE THREAD

**Issue by southxzx** [pubnub/javascript#380]
Hi, i'm using pubnub on my nodejs app. Everything seems to work well but sometime in the middle, I got an error from pubnub and crash my app. I suspect that it comes from the publish method and wrap it within the try-catch block but didn't help. 

Below is the error message I got:

```
/app/node_modules/pubnub/lib/errors/pubnub-api-error.js:137
        return new pubnub_error_1.PubNubError(message !== null && message !== void 0 ? message : this.message, this.toStatus(operation));
               ^
PubNubError: REST API request processing error, check status for details
    at PubNubAPIError.toPubNubError (/app/node_modules/pubnub/lib/errors/pubnub-api-error.js:137:16)
    at /app/node_modules/pubnub/lib/core/pubnub-common.js:299:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by parfeon** [comment]
@southxzx thank you for reaching out to us.

Is there any more details to this error to help us handle the issue better on our end?
