### ISSUE TITLE
Signal event required text params and docs updates

### ISSUE THREAD

**Issue by roman-rr** [pubnub/javascript#387]
I'm trying to send signal as its in [docs](https://www.pubnub.com/docs/sdks/javascript/api-reference/publish-and-subscribe#basic-usage-2)
```javascript
pubnub.signal({
  message: "typing:start",
  channel: "channel_name"
});
```
Then I have successful status on callback, but even't didn't received in any event listener under channel `channel_name` subscriptions. 

When I send it like so:
```javascript
pubnub.signal({
  message: {text: "typing:start"},
  channel: "channel_name"
});
```
Event's successfully received on event listeners. 

### Is it bug or missing ? 
"pubnub" : "8.2.4"

**Comment by parfeon** [comment]
Thank you for reaching us with issue report. 
We've prepared a fix for it, which will be released on Thursday.

**Comment by parfeon** [comment]
It depends on from your needs. If by your application design you need strings, then I would suggest waiting a bit for release.
