### ISSUE TITLE
[BUG] Sets doesn't unsubscribe from channels with -pnpres suffix

### ISSUE THREAD

**Issue by roman-rr** [pubnub/javascript#390]
Please correct me, if not the bag. 

```javascript
// Let's define a subscription set and add some channels with `-pnpres` for presence listening. 
let regularSubscriptionSet = pubnub.subscriptionSet({
  channels: ['channel-1-pnpres', 'channel-2-pnpres', 'channel-3', 'channel-4'],
});

// Subscribe to set
regularSubscriptionSet.subscribe();

// Check subscriptions
console.log('Subscribed channels', pubnub.getSubscribedChannels());
// Returned ['channel-1-pnpres', 'channel-2-pnpres', 'channel-3', 'channel-4']

// Unsubscribe from set 
regularSubscriptionSet.unsubscribe();

console.log('Subscribed channels', pubnub.getSubscribedChannels());
// Returned ['channel-1-pnpres', 'channel-2-pnpres']

// Call depreciated method
pubnub.unsubscribe({channels: ['channel-1-pnpres', 'channel-2-pnpres']})

console.log('Subscribed channels', pubnub.getSubscribedChannels());
// Returned []
```

In other words, new `SubscriptionSet` functionality doesn't unsubscribe from channels with `-pnpres`, even it's bootstrapped to `pubnub.channel()`. 
Old style `pubnub.unsubscribe()` works as expected. 

Did I miss something?

**Comment by parfeon** [comment]
@roman-rr thank you for reporting back about the issue.

I can see in the code special `-pnpres` channels treatment, but need to consult the team about why this decision has been made. It should list of channels and groups as-is, but maybe some factors need to be considered.

**Comment by parfeon** [comment]
Release is rolling out as a temporarily backward-compatible solution.

The idea behind the original implementation was to use the `receivePresenceEvents` subscription configuration option to instruct the subscription object to provide `-pnpres` - this way all works as expected. When they have passed manually, you will get into trouble.
