### ISSUE TITLE
[FEAT] Auto enable receivePresenceEvents for channels with '-pnpres' suffix

### ISSUE THREAD

**Issue by roman-rr** [pubnub/javascript#391]
Please review & consider, if possible to automatically enable `receivePresenceEvents: true` for channels with suffix `-pnpres`, like so: 

```javascript
// Current usage
const subscriptionSet = pubnub.subscriptionSet({ 
    channels: ['ch1', 'ch2'], 
    subscriptionOptions: { receivePresenceEvents: true } 
});

// Possible variation to reduce code base
const subscriptionSet = pubnub.subscriptionSet({ channels: ['ch1-pnpres', 'ch2-pnpres'] });
```

And then both cases will have flag `receivePresenceEvents: true`, which can reduce code double-tube for presence/non-presence channels in client side.

**Comment by parfeon** [comment]
@roman-rr thanks for reaching out to us.

I'm not really sure what you want to achieve. `receivePresenceEvents` - this is a flag which internally used to generate `-pnpres` versions. In first case set will contain: `ch1`, `ch2`, `ch1-pnpres` and `ch2-pnpres` and on subscribe updates will be received from all of them (real-time messages and presence updates). Second example will only listen for presence updates.

**Comment by roman-rr** [comment]
@parfeon Thanks, I already find out.
