### ISSUE TITLE
PNMalformedResponseCategory & PNDecryptionErrorCategory missing after updating to 8.2.8

### ISSUE THREAD

**Issue by conorhooley** [pubnub/javascript#404]
Hello,

As the title indicates, I'm attempting to update our version of pubnub to 8.2.8 and the existing code we have that handles these events is now failing to build as these two events are no longer in the `StatusCategory` type after updating.

I could not find any guidance around, or mention of, this in the JavaScript SDK docs. The chatbot on the site also didn't have any answers. It appears these events also exist in your other SDKs. So I just thought I'd ask here.

![image](https://github.com/user-attachments/assets/d69e3c42-3863-4bed-be52-538915d82fc5)

**Comment by parfeon** [comment]
@conorhooley thank for reporting.

What version you are updating from?

**Comment by conorhooley** [comment]
> @conorhooley thank for reporting.
> 
> What version you are updating from?

8.2.7

**Comment by parfeon** [comment]
This package version finally relies on types definition which is bundled with it. 
With 8.2.7 you probably used `@types/pubnub`? Were you receiving those categories after upgrading to 8.x.x?

**Comment by parfeon** [comment]
Starting from 8.x.x we don't emit those categories. 
Received message (`message` listener) has a `error` field with message (right now it will be set in case of decryption error) and the same field will be for fetch API entry.

**Comment by conorhooley** [comment]
Thanks for the info! I appreciate it.
