### ISSUE TITLE
Incorrect history Actions type

### ISSUE THREAD

**Issue by yo1dog** [pubnub/javascript#407]
The current typing for the history `Actions` interface is wrong. It defines the action value as an object when it is actually an array of objects.

https://github.com/pubnub/javascript/blob/0beda2cb0b80eba69309111fb27a76d8c6319081/src/core/types/api/history.ts#L134-L144

**Comment by parfeon** [comment]
@yo1dog this issue is addressed in [v8.2.10](https://github.com/pubnub/javascript/releases/tag/v8.2.10)
