### ISSUE TITLE
Can not use declaritive import without esModuleInterop

### ISSUE THREAD

**Issue by yo1dog** [pubnub/javascript#410]
Currently, the project-wide `esModuleInterop` flag must be enabled in order to import the `pubnub` module using declarative syntax (`import * as PubNub from 'pubnub'`). Alternatively, dynamic import syntax may be used (`import PubNub = require('pubnub')`), but that carries its own list of disadvantages.

This is fixed by simply declaring a `PubNub` namespace alongside the exported class like so:
```typescript
declare class PubNub ...
declare namespace PubNub {}
export = PubNub;
```

This matches the DefinitelyTyped package: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pubnub/index.d.ts#L330

**Comment by parfeon** [comment]
@yo1dog this issue is addressed in [v8.2.10](https://github.com/pubnub/javascript/releases/tag/v8.2.10)
