### ISSUE TITLE
PublishParameters message type too strict

### ISSUE THREAD

**Issue by yo1dog** [pubnub/javascript#412]
It looks like the `Payload` type used by `PublishParameters.message` attempts to ensure the value contains only valid JSON types, but using this type on inputs prevents users from utilizing the JSON serialization layer. Namely, classes/objects with custom JSON serialization via `toJSON()`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior

For example, instances of `Date`. Another example is that `undefined` is not allowed even though JSON serialization excludes those properties automatically.

I suggest using `unknown` instead of `Payload`.

The workaround is to use the `any` trapdoor which defeats the purpose of the typing entirely.

**Comment by parfeon** [comment]
Thank you for reaching out to us.

`string` is the output of `JSON.stringify` which is an acceptable data type for `PublishParameters.message`.  According to the [RFC-8259](https://datatracker.ietf.org/doc/html/rfc8259#section-3) JSON values should be one of:
- `object` 
- `array`
- `number` 
- `string`
- `false` / `true` / `null`

Serialization / deserialization expected to be done by user.

**Comment by parfeon** [comment]
I still don't understand what is the issue and what redundant calls are done. 

User provides a valid JSON object or `string` (which can be done from dynamic object with `JSON.stringify()` where they will get all conversion out-of-box).
For precision issues, users have a choice: 
- call `JSON.stringify()` and use what it will return with `publish`
- make bigint a string which won't cause precision fluctuation.

**Comment by yo1dog** [comment]
> User provides a valid JSON object or `string`
> ...
> call `JSON.stringify()` and use what it will return with `publish`

No, users cannot provide a JSON string to `publish`. As the docs say:
https://www.pubnub.com/docs/sdks/javascript/api-reference/publish-and-subscribe#message-data

> **Don't use JSON.stringify**
> It is important to note that you should not use JSON.stringify() when sending signals/messages via PubNub. Why? Because the serialization is done for you automatically. Instead just pass the full object as the message payload. PubNub takes care of everything for you.

Indeed, if a user were to pass a JSON string to `publish`, `prepareMessagePayload` would double serialize it by passing it through `JSON.stringfy()` again.

https://github.com/pubnub/javascript/blob/c47f202c2966408e221267ebfd142c64a6ddde85/src/core/endpoints/publish.ts#L214-L221

`pubnub.publish({message: JSON.stringify({fubar: new Date()}))` results in `"{\"fubar\":\"2024-10-29T13:22:10.662Z\"}"`

**Comment by parfeon** [comment]
@yo1dog this issue is addressed in [v8.2.10](https://github.com/pubnub/javascript/releases/tag/v8.2.10)
