### ISSUE TITLE
Parameter bag types with index signatures are too lax

### ISSUE THREAD

**Issue by yo1dog** [pubnub/javascript#413]
In several places, inputs that would otherwise be strictly structured contain index signatures which allow the user to specify properties with any key. This prevents the typings from being able to catch misspellings and other mistakes. Specifically, in argument "bags".

For example, `PublishParameters` contains an index signature "for deprecated parameters", but this allows the following misspelling without any warning or error:
```typescript
pubnub.publish({channel: 'fu', message: 'bar', storeInHistor: false})
```

Without the index signature, Typescript would flag `storeInHistor` with the error: `Object literal may only specify known properties, but 'storeInHistor' does not exist in type 'PublishParameters'. Did you mean to write 'storeInHistory'?`

Rather than an index signature, deprecated params should be explicitly listed but marked as deprecated. Or, a dedicated subkey or alternate param should be provided for specifying arbitrary keys which are merged when sent to the API.

**Comment by parfeon** [comment]
@yo1dog this issue is addressed in [v8.2.10](https://github.com/pubnub/javascript/releases/tag/v8.2.10)
