### ISSUE TITLE
Message Metadata: Allow update via action?

### ISSUE THREAD

**Issue by WalrusSoup** [pubnub/javascript#423]
Right now, the [message actions](https://github.com/pubnub/js-chat/blob/master/lib/src/types.ts#L17) only allow three keys:
reactions, deleted, edited.

When edited is used, it is pretty much hard coded to only be `text` in the chatsdk. It would be nice if we could add another key, `metadata` to allow us to pipe through metadata updates on the original message.

**Comment by parfeon** [comment]
Thank you for reaching out to us!

I think it will be more productive to have these questions in the repo which actually built wrapper around the core SDK (this repo): https://github.com/pubnub/kmp-chat/issues
